### ISSUE TITLE
Adding woocommerce actions and filters

### ISSUE THREAD

**Issue by aolin480** [junichi11/netbeans-wordpress-plugin#15]
I would love to contribute action and filters for one of the most popular ecommerce plugins for this plugin. Do you have a tool that scrapes the do_action and do_filter files to grab the actions or do you enter them in manually? Woocommerce has a page dedicated to all of the actions and filters, but if you have a suggestion on how I can get those from the source files, I can definitely work on that?

I just got started in netbeans 2 weeks ago, and I love the platform for coding.

Thanks!

**Comment by Chris2011** [comment]
I know it is mostly 5 Years old but do you have any news here @aolin480? :D
