### ISSUE TITLE
[request] Plugin, Theme minimum requirement option

### ISSUE THREAD

**Issue by ve3** [junichi11/netbeans-wordpress-plugin#24]
Hello,

This may be feature request. Many time developers make themes or plugins and they have to manually check minimum requirement for each functions they used.

For example: some functions require WordPress 3.4 which means minimum requirement is WP 3.4 or some functions require WordPress 3.5 which means minimum requirement is WP 3.5

It would be very good feature for developers and designers to check their requirement before publish their plugins or themes.

**Comment by Chris2011** [comment]
Maybe the yenta hack can help here: https://bitbucket.org/jglick/yenta
