### ISSUE TITLE
Wordpress compress doesn't do anything.

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-wordpress-plugin#39]
When I select my wp project and go to file and click on "WordPress compress", it seems that it doesn't do anything. What I expect, the project will be packed into an archive or not?

Regards

Chris

**Comment by Chris2011** [comment]
Ok I understand it, but it should do smth. Maybe a dialog where it says "Themes and plugins where compressed" or whatever. For me it is a button/link without any function. Your feedback was nice, but this feedback is missing in the functionality of this button.

**Comment by junichi11** [comment]
I'll fix it. Show the action in the context menu when selected node is a theme or plugin root directory.

Thanks.

**Comment by junichi11** [comment]
**NOTE** Remove `File > WordPress Zip compress` to prevent confusing.

**Comment by Chris2011** [comment]
It works, thx :)
