### ISSUE TITLE
Uninitialized variable

### ISSUE THREAD

**Issue by Mte90** [junichi11/netbeans-wordpress-plugin#40]
Netbeans alert this variables for not uninitialized but they are initialized by wordpress so is an useless alert:

```
$before_widget
$after_widget
$before_title
$after_title
```

Is possible create a list for disable this alert?
The variables are many other but actually i've founded this.

**Comment by Mte90** [comment]
it is very annoying...

**Comment by junichi11** [comment]
Unfortunately, It is not this plugin's problem. 
If you don't show them, please uncheck Tools > Options > Editor > Hints > PHP > Uninitialized Variables.
But please note that it means all Uninitialized Hints are not checked.

Thanks.
