### ISSUE TITLE
Autocomplete does not work

### ISSUE THREAD

**Issue by andreasbaumde** [junichi11/netbeans-wordpress-plugin#44]
Hello, 

The autocomplete function is not working in my own theme. In other themes the function is working perfectly. 

What can I do to achieve the correct function? 

NetBeans IDE 8.0.2 (Build 201411181905)
PHP WordPress Blog/CMS Version: 0.7.3

Thanks in advance. 

Best Regards

**Comment by junichi11** [comment]
Hi, 

> The autocomplete function

What does this mean? If it means code completions for wp functions(methods) and variables, it is not plugin's problem.

**Comment by andreasbaumde** [comment]
Oh, you are right. My bad. Sorry for the circumstance. 

Really good plugin!

**Comment by junichi11** [comment]
@andreasbaumde Did you resolve it? I replied for your post on NetBeans forum.

**Comment by Omarchio** [comment]
Hello i resolve this problem: go to -> tools -> options -> tab( editor) -> tab (code completion) -> select languaje and modify options and try write. Enjoy.
