### ISSUE TITLE
Upload on Run - save previous selection

### ISSUE THREAD

**Issue by Sawascwoolf** [junichi11/netbeans-wordpress-plugin#46]
Hi,

I'm not sure if it is possible to implement this with your plugin or if it is a core issue.

I'm developing Wordpress Plugins and it would be nice if NB could remember the last selection for uploading the files to ftp at runtime.
It is really annoying to click through the folders to select the single plugin again and again.

**Comment by junichi11** [comment]
> I'm not sure if it is possible to implement this with your plugin or if it is a core issue.

If your problem is related to the ftp feature,  please submit your request to NetBeans bugzilla because I can't fix it. 

> I'm developing Wordpress Plugins and it would be nice if NB could remember the last selection for uploading the files to ftp at runtime.
> It is really annoying to click through the folders to select the single plugin again and again.

I'm not sure what you expect yet. Please write your steps.

Does it mean the following?
Project Properties > Run Configulation : 
Run As : Remote Web Site(FTP, SFTP)
Upload Files: On Run

**Comment by Sawascwoolf** [comment]
You've got my settings.

I'm developing a plugin, so I only change code inside this specific folder. When pressing F6 (run command) bugzilla shows up to select which files should be uploaded. 
Every time of this procedure I have to navigate to the whole folder tree of wordpress to select my plugins folder. 

There are two different possible behaviours I would like to see:
1. Remember the selection from the last run-action (I think I will have to file this request to the bugzilla repo)
2. Enable the shortcut to themes and plugins as in the project tree (this will reduce the navigation through the folder tree by two steps.)

**Comment by junichi11** [comment]
Your request seems to be related to the ftp and run features. Please submit your issues to NetBeans bugzilla because I can't fix them.
