### ISSUE TITLE
Notification link that there is a new version of WP doesn't do anything.

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-wordpress-plugin#47]
When I click on the link, that it says to me, that there is a new version available, it doesn't do anything. What I expect maybe open the browser and go to the page to download the new package or please implement a whole update process for wordpress as I can do it inside the wordpress backend, as an administrator. That would be nice.

Regards

Chris

**Comment by junichi11** [comment]
AFAIR, if you set wp-cli to the global Options, perhaps update command is run.
So, I'll improve a bit(Show a dialog if it is not set).

Thanks.

**Comment by junichi11** [comment]
Version for testing is the following: 
https://github.com/junichi11/netbeans-wordpress-plugin/releases/tag/v0.7.3 (0.7.3.2-dev)

Thanks.

**Comment by junichi11** [comment]
If you have some issues, please reopen it.

Thanks.
