### ISSUE TITLE
Feature request: add .htaccess in Impo(r)tant Files

### ISSUE THREAD

**Issue by bastienho** [junichi11/netbeans-wordpress-plugin#50]
Hi,

In many cases, `.htaccess` file is as important as wp-config.php

Could you add it in the list of important files?

By the way, there is a typo in the README **Impo(r)tant** ;)

regards

**Comment by junichi11** [comment]
> In many cases, .htaccess file is as important as wp-config.php
> Could you add it in the list of important files?

I'll do that. But probably only the one file in the root directory...

> By the way, there is a typo in the README Impo(r)tant ;)

Oops, thanks for letting me know :)

**Comment by junichi11** [comment]
Fixed. But check only the root directory.

https://github.com/junichi11/netbeans-wordpress-plugin/releases/tag/v0.8.2

**Comment by bastienho** [comment]
Many thanks, much appreciated

**Comment by junichi11** [comment]
You're welcome :)
