### ISSUE TITLE
WordPress Zip Compressor

### ISSUE THREAD

**Issue by ioannup** [junichi11/netbeans-wordpress-plugin#55]
If you created zip-file and then try to display context menu again - you get this error. http://i.imgur.com/SrF3OlP.png

**Comment by junichi11** [comment]
Yes, it's correct behavior. It avoids to overwrite the file. But I can improve a bit. e.g. Show the confirmation message to overwrite it. What do you think?

**Comment by ioannup** [comment]
Maybe. But I think this message needs to display after you click on the corresponding menu "WordPress Zip Compressor" instead of each call of the context menu.

**Comment by junichi11** [comment]
Fixed.

https://github.com/junichi11/netbeans-wordpress-plugin/releases/tag/v0.8.3
