### ISSUE TITLE
Configuration for plugin project

### ISSUE THREAD

**Issue by truckee** [junichi11/netbeans-wordpress-plugin#58]
A Netbeans 8.2 project has been created in a plugin's directory, mostly to make .gitignore easier to build.  The project is in Windows 10. If this project can be configured as a WordPress framework, what exactly are the correct entries to avoid `Existing WordPress Root directory name must be set.`  The following does NOT work:
````
Custom content name: ../../../wp-content (or ..\..\..\wp-content)
    WordPress root: ..\..\..\..\uufnn
    plugins: ..\..\plugins
    themes: ..\..\themes
````
The parameters above do point to their respective directories from the project root.
Or is it not feasible to create a WordPress project so deeply inside WP itself?

**Comment by junichi11** [comment]
Please use the relative path from the Source Directory of your project.
In the following case, WordPress Root: ../wp-root (please try to use not "\" but "/")
```
├── wp-root
│   ├── wp-admin
│   ├── wp-content
│   └── wp-include
├── "your source directory"
│   ├── nbproject
│   ├── ....
│   └── ....
```
In the following case, WordPress Root: ../../wp-root
```
├── wp-root
│   ├── wp-admin
│   ├── wp-content
│   ├── "your source directory"
│   │   ├── nbproject
│   │   ├── ....
│   │   └── ....
│   └── wp-include
```

**Comment by truckee** [comment]
Thanks.  I got it sorted.
````
Custom content name: wp-content
    WordPress root: ../../../../uufnn
    plugins: ../../plugins
    themes: ../../themes
````
