### ISSUE TITLE
Option to only create a blank theme with style.css and index.php

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-wordpress-plugin#59]
In general, if you want to create your own theme, you only need 2 files: style.css and index.php.
In the style.css there will be your options from actions -> WordPress -> Create Theme -> Underscores.
So we have Backbones and Underscores, a new entry called "Blank Theme", "Custom Theme" or "Empty Theme" with the dialog to set the name, author etc. and to only have a folder with your name and style.css and index.php inside of it, would be very handy.

Cheers

Chris

**Comment by junichi11** [comment]
Done.
