### ISSUE TITLE
Set action WordPress to specific, new created nodes.

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-wordpress-plugin#60]
Your plugin creates a plugins node and a themes node. It would be great, if I can right click on the plugins folder and choose WordPress -> Create plugin (For the plugin node) and WordPress -> Create Theme/Create ChildTheme (FOr the themes node).

It will reduce the time to not choose New -> Others -> DIalog open -> Search for WordPress -> Choose what you want.

Cheers

Chris

**Comment by junichi11** [comment]
Done.
