### ISSUE TITLE
WordPress composer support

### ISSUE THREAD

**Issue by llaumgui** [junichi11/netbeans-wordpress-plugin#62]
#### Issue type

- [ ] Bug
- [x] Enhancement

#### Overview description

Support of WordPress instance with Composer (wp-content not in root folder).

```
├───vendor
├───web
│   ├───wp => My WordPress root
│   ├───wp-content
```

#### Steps to reproduce

1. Try to configure Netbeans with a wp-content folder not in the root folder
2. Can't save.

**Comment by junichi11** [comment]
Could you write your steps for installing WordPress with composer?

**Comment by llaumgui** [comment]
I used this article : https://pantheon.io/blog/web-docroot-wordpress-composer

**Comment by junichi11** [comment]
Thanks!

**Comment by junichi11** [comment]
Give it a try! : 0.9.2.1-dev https://github.com/junichi11/netbeans-wordpress-plugin/releases/tag/v0.9.2

If you find a problem, please let me know.

**Comment by llaumgui** [comment]
Nice !
