### ISSUE TITLE
wp-cli can't be found when globally installed

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-wordpress-plugin#63]
#### Issue type

- [x] Bug
- [ ] Enhancement

#### Overview description
I installed wp-cli via composer with `composer global require wp-cli/wp-cli`. When I click `search` in NetBeans, it says: `No wp-cli scripts found.`

The paths, where it was installed are:

`C:\Users\Chrl\AppData\Roaming\Composer\vendor\bin\wp`
`C:\Users\Chrl\AppData\Roaming\Composer\vendor\bin\wp.bat`

#### Steps to reproduce

1. Open NetBeans with WordPress plugin
2. Install composer
3. Install wp-cli via composer `composer global require wp-cli/wp-cli`
4. Go th NetBeans options -> PHP -> Frameworks & Tools -> WordPress
5. Click on Search

#### Actual results
An popup opens and it says: `No wp-cli scripts found`

#### Expected results
It should appear inside the browse input field.

#### Your environment (NetBeans and plugin version, e.t.c.)
Windows 10, NetBeans 8.2, WordPress Plugin 0.9.2, PHP 7.1.1

**Comment by Chris2011** [comment]
Maybe it is because of an old path or changed name. The plugin should handle the old variant and the new path/name. If there was a change. Now it is `wp` or `wp.bat`. As far as I can see, you expect wp or `wp-cli.phar`

**Comment by junichi11** [comment]
Done. https://github.com/junichi11/netbeans-wordpress-plugin/releases/tag/v0.9.3 0.9.3.1-dev

*NOTE*:  Probably, you have to add `C:\Users\Chrl\AppData\Roaming\Composer\vendor\bin` to your `PATH` (Path environment variable).

**Comment by Chris2011** [comment]
Thx for the hint, the composer executable, does it automatically.
