### ISSUE TITLE
There is no available installation method.

### ISSUE THREAD

**Issue by accountsguy** [junichi11/netbeans-wordpress-plugin#65]
I have installed NetBeans 8.2 and installed Plugin PHP WordPress Blog/CMS

After i have selected the Wordpress PHP Web Blog/CMS for PHP Framework i see the following error message

**There is no available installation method.**

What is the solution for this one.

**Comment by junichi11** [comment]
Can you write exact steps to reproduce it? Is there a screenshot?

**Comment by accountsguy** [comment]
Creating a New Project > PHP > PHP Application

In the PHP Framework step when i select the Wordpress PHP Web Blog/CMS (Wordpress Plugin) i see this error.

**Comment by accountsguy** [comment]
That is really great, the error gone and in the final stage it gives the following error 

**Cannot unzip : http://wordpress.org/latest.zip**

**Comment by junichi11** [comment]
If you set it to "Local file path", it is a correct error.
You have to download it to your local PC. Your environment is not connected to the Internet, right?

**Comment by accountsguy** [comment]
Is there any Environmental setting needs to be configured for url to unzip the Wodpress file?

**Comment by junichi11** [comment]
When your PC is connected to the Internet, the plugin can download a zip file from the WordPress site. Otherwise, you have to download the zip file once somewhere, then have to set the file path to the Options.
Because WordPress files are not bundled with this plugin.

**Comment by accountsguy** [comment]
Thanks a lot even the url is not working we need to provide that one also including the local path for the zip file of the Wordpress. Now it is working properly thanks
