### ISSUE TITLE
Duplicate entries in Run WordPress Command window

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-wordpress-plugin#66]
#### Issue type

- [x] Bug
- [ ] Enhancement

#### Overview description
Inside the "Run WordPress Command" window, when I filter for "plugin" for example, I see duplicate entries.

#### Steps to reproduce

1. Open Run WordPress Command window
2. Filter for plugin
3. See the result

#### Actual results
Duplicate entries

#### Expected results
No duplicates

#### Your environment (NetBeans and plugin version, e.t.c.)
NetBeans 8.2, PHP WordPress Blog/CMS 0.9.4

![duplicate-entries](https://user-images.githubusercontent.com/795658/41841838-97ab7738-7869-11e8-8d87-5c55b38cec09.png)

Cheers

Chris

**Comment by junichi11** [comment]
If your problem occurs still with the new nbm, please reopen this.

**Comment by Chris2011** [comment]
Will try version 0.9.5. Thx.

**Comment by Chris2011** [comment]
Seems to work. Thx :)
