### ISSUE TITLE
Enhancement Request: Netbeans 10 Support

### ISSUE THREAD

**Issue by gituser2a** [junichi11/netbeans-wordpress-plugin#73]
#### Issue type

- [] Bug
- [x] Enhancement

#### Overview description

The Plugin is not available in the plugin repository of Netbeans 10. 

Netbeans 10 is out now for some weeks and has now again the great PHP support of v8. But I'm missing the wordpress plugin, which ist not listed under Tools->Plugins->Available Plugins in Netbeans 10. Please integrate it again.

#### Your environment (NetBeans and plugin version, e.t.c.)

Netbeans 10 on Linux

**Comment by junichi11** [comment]
I've requested verification. http://plugins.netbeans.org/plugin/46542/php-wordpress-blog-cms
So, if it passed, we can install the plugin via NetBeans itself again :)
