### ISSUE TITLE
The plugin PHP Editor is requested in implementation version 2.

### ISSUE THREAD

**Issue by webformation** [junichi11/netbeans-wordpress-plugin#74]
#### Issue type

- [x] Bug
- [ ] Enhancement

#### Overview description
Impossible to install the plugin on Netbeans 12.2

#### Steps to reproduce

1. installation of plugin
2. 
3. 

#### Actual results
Error box with the message "The plugin PHP Editor is requested in implementation version 2."

#### Your environment (NetBeans and plugin version, e.t.c.)
Netbeans 12.2
Windows 10

**Comment by junichi11** [comment]
Could you please use 1.2.0? https://github.com/junichi11/netbeans-wordpress-plugin/releases/tag/v1.2.0
Unfortunately, we can't add this to Plugin Portal, sorry.

**Comment by webformation** [comment]
It works well !

Thank you

**Comment by petruciucur** [comment]
Wordpress CMS Plugin is not install in Netbeans 12.3

**Comment by junichi11** [comment]
@petruciucur Did you try to use this? https://github.com/junichi11/netbeans-wordpress-plugin/releases/tag/v1.2.0 

As I wrote above, we can't add this to Plugin Portal, sorry.
See: https://issues.apache.org/jira/browse/NETBEANS-5064

**Comment by petruciucur** [comment]
> @petruciucur Did you try to use this? https://github.com/junichi11/netbeans-wordpress-plugin/releases/tag/v1.2.0
> 
> As I wrote above, we can't add this to Plugin Portal, sorry.
> See: https://issues.apache.org/jira/browse/NETBEANS-5064

Installed, thanks a lot.
